# Generated by Django 5.2.15 on 2026-09-15 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThaiReportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='批次名')),
                ('status', models.CharField(choices=[('PENDING', '处理中'), ('DONE', '已完成'), ('FAILED', '失败')], default='PENDING', max_length=20)),
                ('patient_file', models.FileField(upload_to='extensions/thai_report/uploads/', verbose_name='样本信息表')),
                ('result_file', models.FileField(upload_to='extensions/thai_report/uploads/', verbose_name='结果表')),
                ('total', models.IntegerField(default=0, verbose_name='样本总数')),
                ('success', models.IntegerField(default=0, verbose_name='成功')),
                ('failed', models.IntegerField(default=0, verbose_name='失败')),
                ('skipped', models.IntegerField(default=0, verbose_name='跳过')),
                ('message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '泰国报告批次',
                'verbose_name_plural': '泰国报告批次',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ThaiReportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(max_length=100)),
                ('accession_id', models.CharField(blank=True, default='', max_length=100)),
                ('option', models.CharField(blank=True, default='', max_length=50)),
                ('result_filter', models.CharField(blank=True, default='', max_length=100)),
                ('template', models.CharField(blank=True, default='', max_length=50)),
                ('report_file', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(blank=True, default='', max_length=20)),
                ('message', models.TextField(blank=True, default='')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='extensions.thaireportbatch')),
            ],
            options={
                'verbose_name': '泰国报告样本',
                'verbose_name_plural': '泰国报告样本',
                'ordering': ['id'],
            },
        ),
    ]
