# Generated by Django 5.2.14 on 2026-06-11 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0003_add_step_qc_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplerun',
            name='extraction_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='samplerun',
            name='extraction_method',
            field=models.CharField(blank=True, choices=[('MANUAL', 'Manual (手动提取)'), ('MAGNETIC_ROD', 'Magnetic Rod (磁棒法)'), ('AUTOMATED', 'Automated Workstation (自动化移液工作站)')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='samplerun',
            name='region',
            field=models.CharField(blank=True, choices=[('THAILAND', '泰国'), ('XIAMEN', '厦门'), ('HONGKONG', '香港'), ('BRAZIL', '巴西')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='samplerun',
            name='run_number',
            field=models.CharField(db_index=True, max_length=30, unique=True),
        ),
    ]
