# Generated by Django 5.2.14 on 2026-06-15 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0004_samplerun_extraction_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplerun',
            name='library_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='samplerun',
            name='library_method',
            field=models.CharField(blank=True, choices=[('SINGLE_CHANNEL', '单枪建库'), ('MULTI_CHANNEL', '排枪建库'), ('AUTOMATED', '自动化移液工作站建库')], default='', max_length=20),
        ),
    ]
