# Generated by Django 5.2.14 on 2026-06-16 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0005_add_library_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplerun',
            name='bioinformatics_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
