# Generated by Django 5.2.14 on 2026-06-11 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0013_add_received_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='receiving_photos',
        ),
        migrations.AddField(
            model_name='sample',
            name='acceptance_date',
            field=models.DateField(blank=True, help_text='Sample acceptance date', null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='all_chrom',
            field=models.CharField(blank=True, default='', help_text='All chromosome result', max_length=20),
        ),
        migrations.AddField(
            model_name='sample',
            name='clinical_diagnosis',
            field=models.TextField(blank=True, default='', help_text='Clinical diagnosis / adverse pregnancy history'),
        ),
        migrations.AddField(
            model_name='sample',
            name='external_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='sample',
            name='fedex_no',
            field=models.CharField(blank=True, default='', help_text='FedEx tracking number', max_length=50),
        ),
        migrations.AddField(
            model_name='sample',
            name='fetal_fraction',
            field=models.FloatField(blank=True, help_text='Fetal fraction percentage', null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='gender',
            field=models.CharField(blank=True, default='', help_text='Fetal gender prediction', max_length=10),
        ),
        migrations.AddField(
            model_name='sample',
            name='gestational_weeks',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='id_card',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='sample',
            name='ivf_status',
            field=models.BooleanField(default=False, help_text='IVF conception'),
        ),
        migrations.AddField(
            model_name='sample',
            name='last_menstrual_period',
            field=models.DateField(blank=True, help_text='Last menstrual period', null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='maternal_bmi',
            field=models.FloatField(blank=True, help_text='Maternal BMI', null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='maternal_weight',
            field=models.FloatField(blank=True, help_text='Maternal weight in kg', null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='multiple_gestation',
            field=models.BooleanField(default=False, help_text='Multiple gestation (twins etc.)'),
        ),
        migrations.AddField(
            model_name='sample',
            name='other',
            field=models.CharField(blank=True, db_column='other_col', default='', help_text='Other notes', max_length=500),
        ),
        migrations.AddField(
            model_name='sample',
            name='physician',
            field=models.CharField(blank=True, default='', help_text='Referring physician', max_length=100),
        ),
        migrations.AddField(
            model_name='sample',
            name='pregnancy_history',
            field=models.CharField(blank=True, default='', help_text='Pregnancy history (gravida/para)', max_length=500),
        ),
        migrations.AddField(
            model_name='sample',
            name='report_code',
            field=models.CharField(blank=True, default='', help_text='Report code from external lab (Thai/Brazil)', max_length=50),
        ),
        migrations.AddField(
            model_name='sample',
            name='send_report_id',
            field=models.CharField(blank=True, default='', help_text='Send report ID', max_length=50),
        ),
        migrations.AddField(
            model_name='sample',
            name='t13',
            field=models.CharField(blank=True, default='', help_text='T13 result', max_length=20),
        ),
        migrations.AddField(
            model_name='sample',
            name='t18',
            field=models.CharField(blank=True, default='', help_text='T18 result', max_length=20),
        ),
        migrations.AddField(
            model_name='sample',
            name='t21',
            field=models.CharField(blank=True, default='', help_text='T21 result', max_length=20),
        ),
        migrations.AddField(
            model_name='sample',
            name='test_option',
            field=models.CharField(blank=True, default='', help_text='Test option (basic/basic_all/plus)', max_length=20),
        ),
        migrations.AddField(
            model_name='sample',
            name='xo',
            field=models.CharField(blank=True, default='', help_text='XO result', max_length=20),
        ),
        migrations.AddField(
            model_name='sample',
            name='xxx',
            field=models.CharField(blank=True, db_column='xxx_col', default='', help_text='XXX result', max_length=20),
        ),
        migrations.AddField(
            model_name='sample',
            name='xxy',
            field=models.CharField(blank=True, default='', help_text='XXY result', max_length=20),
        ),
        migrations.AddField(
            model_name='sample',
            name='xyy',
            field=models.CharField(blank=True, default='', help_text='XYY result', max_length=20),
        ),
        migrations.AddField(
            model_name='sample',
            name='zscore_13',
            field=models.FloatField(blank=True, help_text='Z-score for chromosome 13', null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='zscore_18',
            field=models.FloatField(blank=True, help_text='Z-score for chromosome 18', null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='zscore_21',
            field=models.FloatField(blank=True, help_text='Z-score for chromosome 21', null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='status',
            field=models.CharField(choices=[('REGISTERED', 'Registered'), ('RECEIVED', 'Received'), ('PRE_PROCESSING', 'Pre-Processing'), ('REJECTED', 'Rejected'), ('IN_PROCESS', 'In Process'), ('TESTING', 'Testing'), ('ANALYZING', 'Analyzing'), ('COMPLETED', 'Completed'), ('REPORTED', 'Reported'), ('ARCHIVED', 'Archived'), ('DISPOSED', 'Disposed')], db_index=True, default='REGISTERED', max_length=20),
        ),
    ]
