# Generated by Django 5.2.14 on 2026-06-11 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0014_remove_sample_receiving_photos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='vg_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='VG internal lab ID', max_length=50),
        ),
    ]
