# Generated by Django 5.2.15 on 2026-06-17 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0015_sample_vg_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='status',
            field=models.CharField(choices=[('REGISTERED', 'Registered'), ('RECEIVED', 'Received'), ('PRE_PROCESSING', 'Pre-Processing'), ('REJECTED', 'Rejected'), ('IN_PROCESS', 'In Process'), ('EXTRACTION', 'NIPT — 核酸提取'), ('LIBRARY_PREP', 'NIPT — 文库构建'), ('POOLING', 'NIPT — 文库定量及Pooling'), ('SEQUENCING', 'NIPT — 上机测序'), ('BIOINFORMATICS', 'NIPT — 生物信息分析'), ('TESTING', 'Testing'), ('ANALYZING', 'Analyzing'), ('COMPLETED', 'Completed'), ('REPORTED', 'Reported'), ('ARCHIVED', 'Archived'), ('DISPOSED', 'Disposed')], db_index=True, default='REGISTERED', max_length=20),
        ),
    ]
