# Generated by Django 5.2.15 on 2026-06-23 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0015_sample_vg_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='source_institution',
        ),
        migrations.AddField(
            model_name='sample',
            name='sample_source',
            field=models.CharField(blank=True, help_text='Sample source institution', max_length=200),
        ),
        migrations.AlterField(
            model_name='sample',
            name='status',
            field=models.CharField(choices=[('REGISTERED', 'Registered'), ('RECEIVING', 'Receiving'), ('RECEIVED', 'Received'), ('ACCEPTED', 'Accepted'), ('PRE_PROCESSING', 'Pre-Processing'), ('REJECTED', 'Rejected'), ('IN_PROCESS', 'In Process'), ('PLASMA_SEPARATED', '血浆已分离'), ('EXTRACTION', 'NIPT — 核酸提取'), ('LIBRARY_PREP', 'NIPT — 文库构建'), ('POOLING', 'NIPT — 文库定量及Pooling'), ('SEQUENCING', 'NIPT — 上机测序'), ('BIOINFORMATICS', 'NIPT — 生物信息分析'), ('TESTING', 'Testing'), ('ANALYZING', 'Analyzing'), ('COMPLETED', 'Completed'), ('REPORTED', 'Reported'), ('ARCHIVED', 'Archived'), ('DISPOSED', 'Disposed')], db_index=True, default='REGISTERED', max_length=20),
        ),
    ]
