# Generated by Django 5.2.15 on 2026-06-29 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0016_add_missing_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='balance',
            field=models.CharField(blank=True, default='', help_text='Balance (Brazil-specific)', max_length=50),
        ),
        migrations.AddField(
            model_name='sample',
            name='gender_info',
            field=models.CharField(blank=True, default='', help_text='Gender info / fetal gender (Brazil-specific)', max_length=50),
        ),
        migrations.AddField(
            model_name='sample',
            name='price',
            field=models.CharField(blank=True, default='', help_text='Price (Brazil-specific)', max_length=50),
        ),
        migrations.AddField(
            model_name='sample',
            name='report_due_date',
            field=models.CharField(blank=True, default='', help_text='Report due date (Brazil-specific)', max_length=50),
        ),
        migrations.AddField(
            model_name='sample',
            name='sinal',
            field=models.CharField(blank=True, default='', help_text='Sinal/deposit (Brazil-specific)', max_length=50),
        ),
    ]
