# Generated by Django 5.2.15 on 2026-09-22 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0018_sample_experiment_history_sample_plasma_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='received_by_name',
            field=models.CharField(blank=True, default='', help_text='Receiver name typed at acceptance (not bound to a Receiver account)', max_length=50),
        ),
    ]
