# Generated by Django 5.2.14 on 2026-06-11 02:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0003_receiver'),
        ('samples', '0014_remove_sample_receiving_photos_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlasmaSeparationBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_number', models.CharField(db_index=True, max_length=30, unique=True)),
                ('experiment_date', models.DateField()),
                ('experiment_time', models.TimeField()),
                ('equipment_type', models.CharField(choices=[('HIGH_SPEED', 'High-Speed Centrifuge'), ('LOW_SPEED', 'Low-Speed Centrifuge')], max_length=20)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], db_index=True, default='IN_PROGRESS', max_length=20)),
                ('operator_signature', models.ImageField(blank=True, null=True, upload_to='plasma_separation/signatures/')),
                ('reviewer_signature', models.ImageField(blank=True, null=True, upload_to='plasma_separation/signatures/')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plasma_batches_operated', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plasma_batches_reviewed', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plasma_batches', to='organizations.site')),
            ],
            options={
                'db_table': 'plasma_separation_batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlasmaSeparationPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='plasma_separation/photos/')),
                ('caption', models.CharField(blank=True, default='', max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='plasma_separation.plasmaseparationbatch')),
            ],
            options={
                'db_table': 'plasma_separation_photos',
            },
        ),
        migrations.CreateModel(
            name='PlasmaSeparationSample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qc_result', models.CharField(choices=[('PENDING', 'Pending'), ('PASS', 'Pass'), ('FAIL', 'Fail')], default='PENDING', max_length=20)),
                ('qc_reason', models.CharField(blank=True, default='', max_length=50)),
                ('notes', models.CharField(blank=True, default='', max_length=200)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_samples', to='plasma_separation.plasmaseparationbatch')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plasma_separation_results', to='samples.sample')),
            ],
            options={
                'db_table': 'plasma_separation_samples',
                'unique_together': {('batch', 'sample')},
            },
        ),
    ]
