# Generated by Django 5.2.14 on 2026-06-11 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plasma_separation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plasmaseparationbatch',
            name='operator_signature_data',
            field=models.JSONField(blank=True, default=dict, help_text='operator {username, signed_at}'),
        ),
        migrations.AddField(
            model_name='plasmaseparationbatch',
            name='reviewer_signature_data',
            field=models.JSONField(blank=True, default=dict, help_text='reviewer {username, signed_at}'),
        ),
    ]
