# Generated by Django 5.2.14 on 2026-06-11 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plasma_separation', '0002_plasmaseparationbatch_operator_signature_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plasmaseparationbatch',
            name='equipment_type',
            field=models.CharField(blank=True, default='HIGH_SPEED', help_text='Comma-separated: HIGH_SPEED,LOW_SPEED', max_length=50),
        ),
    ]
