# Generated by Django 5.2.15 on 2026-06-30 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plasma_separation', '0003_alter_plasmaseparationbatch_equipment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='plasmaseparationsample',
            name='plasma_count',
            field=models.PositiveSmallIntegerField(default=3, help_text='该样本本次分离所得血浆份数'),
        ),
    ]
