# Generated by Django
from django.conf import settings
from django.db import migrations, models
import uuid

class Migration(migrations.Migration):
    initial = True
    dependencies = [
        ('organizations', '0001_initial'),
        ('samples', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('case_number', models.CharField(db_index=True, max_length=30, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('REGISTERED', 'Registered'), ('RECEIVING', 'Receiving'), ('IN_PROCESS', 'In Process'), ('COMPLETED', 'Completed'), ('REPORTED', 'Reported'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20)),
                ('gestational_age_weeks', models.PositiveIntegerField(blank=True, null=True)),
                ('gestational_age_days', models.PositiveIntegerField(blank=True, null=True)),
                ('clinic_name', models.CharField(blank=True, max_length=200)),
                ('clinic_contact', models.CharField(blank=True, max_length=100)),
                ('sales_person', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('is_urgent', models.BooleanField(default=False)),
                ('expected_completion', models.DateField(blank=True, null=True)),
                ('registration_token', models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True)),
                ('registration_token_expires', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=models.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('panel', models.ForeignKey(on_delete=models.PROTECT, related_name='cases', to='samples.TestPanel')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=models.PROTECT, related_name='cases', to='organizations.Site')),
            ],
            options={
                'db_table': 'cases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseSample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('MOTHER', 'Mother'), ('ALLEGED_FATHER', 'Alleged Father')], db_index=True, max_length=20)),
                ('sample_source', models.CharField(choices=[('BLOOD', 'Peripheral Blood'), ('SWAB', 'Buccal Swab'), ('HAIR', 'Hair Follicle'), ('DBS', 'Dried Blood Spot')], default='BLOOD', max_length=10)),
                ('ethnicity', models.CharField(blank=True, max_length=50)),
                ('relationship_to_mother', models.CharField(blank=True, max_length=50)),
                ('receipt_photo', models.ImageField(blank=True, null=True, upload_to='cases/receipts/')),
                ('receipt_condition', models.CharField(blank=True, max_length=30)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('collection_site', models.CharField(blank=True, max_length=100)),
                ('collection_notes', models.TextField(blank=True)),
                ('test_sample_id', models.CharField(blank=True, db_index=True, max_length=40, null=True, unique=True)),
                ('resample_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=models.CASCADE, related_name='case_samples', to='cases.Case')),
                ('received_by', models.ForeignKey(null=True, on_delete=models.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('resample_of', models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL, related_name='resamples', to='cases.CaseSample')),
                ('sample', models.OneToOneField(on_delete=models.CASCADE, related_name='case_sample', to='samples.Sample')),
            ],
            options={
                'db_table': 'case_samples',
                'ordering': ['role', 'created_at'],
                'unique_together': {('case', 'sample')},
            },
        ),
    ]
