# Generated by Django 5.2.15 on 2026-07-21 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_initial_fix'),
    ]

    operations = [
    ]
