# Generated by Django 5.2.15 on 2026-07-21 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_case_pt_number_alter_casesample_resample_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='applicant',
            field=models.CharField(blank=True, default='', help_text='申请方', max_length=200),
        ),
        migrations.AddField(
            model_name='case',
            name='email',
            field=models.EmailField(blank=True, default='', help_text='邮箱', max_length=200),
        ),
        migrations.AddField(
            model_name='case',
            name='multiple_gestation',
            field=models.BooleanField(default=False, help_text='单双胎: False=单胎, True=双胎'),
        ),
        migrations.AddField(
            model_name='case',
            name='phone',
            field=models.CharField(blank=True, default='', help_text='联系电话', max_length=30),
        ),
        migrations.AddField(
            model_name='case',
            name='registration_type',
            field=models.CharField(choices=[('FIRST', '首次检测'), ('SUPPLEMENT', '补充样本'), ('RESAMPLE', '重采样本')], default='FIRST', max_length=20),
        ),
        migrations.AddField(
            model_name='case',
            name='risk_warnings',
            field=models.JSONField(blank=True, default=list, help_text='影响结果的风险提示'),
        ),
        migrations.AddField(
            model_name='casesample',
            name='arrival_date',
            field=models.DateField(blank=True, help_text='到样日期', null=True),
        ),
    ]
