# Generated by Django 5.2.15 on 2026-07-22 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_case_applicant_case_email_case_multiple_gestation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casesample',
            name='actual_sample_type',
            field=models.CharField(blank=True, default='', help_text='实际收到的样本类型（可能与登记不同）', max_length=10),
        ),
        migrations.AddField(
            model_name='casesample',
            name='preservation_method',
            field=models.CharField(blank=True, default='', help_text='保温措施: 无/冰袋/暖宝宝', max_length=20),
        ),
    ]
