# Generated by Django 5.2.15 on 2026-07-22 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_add_receiving_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casesample',
            name='sample_source',
            field=models.CharField(choices=[('BLOOD', '血液'), ('DBS', '血痕'), ('HAIR', '毛发'), ('SWAB', '口拭子'), ('NAIL', '指甲'), ('SEMEN', '精液'), ('TOOTHBRUSH', '牙刷'), ('CIGARETTE', '烟头'), ('BOTTLE', '水瓶')], default='BLOOD', max_length=10),
        ),
        migrations.AlterField(
            model_name='casesample',
            name='test_sample_id',
            field=models.CharField(blank=True, db_index=True, help_text='PT test sample ID, e.g. PT00123M, PT00123Fa', max_length=40, null=True),
        ),
    ]
