# Generated manually for Phase 1: 5 independent NIPPT modules
from django.db import migrations, models
import django.db.models.deletion
import uuid
from django.conf import settings

class Migration(migrations.Migration):
    dependencies = [
        ('cases', '0008_nippt_preprocessing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]
    operations = [
        migrations.CreateModel(
            name='NipptExtractionBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_number', models.CharField(db_index=True, max_length=30, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', '待处理'), ('IN_PROGRESS', '处理中'), ('COMPLETED', '已完成')], db_index=True, default='DRAFT', max_length=20)),
                ('extraction_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={'db_table': 'nippt_extraction_batches', 'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='NipptExtractionSample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('MOTHER', 'Mother'), ('ALLEGED_FATHER', 'Alleged Father')], db_index=True, max_length=20)),
                ('category', models.CharField(choices=[('FEMALE_BLOOD', '女性血液'), ('MALE_BLOOD', '男性血液'), ('MALE_OTHER', '男性其他')], db_index=True, max_length=20)),
                ('case_sample_ids', models.JSONField(default=list)),
                ('source_preprocessing_sample_id', models.UUIDField(blank=True, null=True)),
                ('extraction_method', models.CharField(blank=True, default='', max_length=20)),
                ('well_position', models.CharField(blank=True, default='', max_length=4)),
                ('plasma_volume', models.FloatField(blank=True, null=True)),
                ('elution_volume', models.FloatField(blank=True, default=55, null=True)),
                ('dna_concentration', models.FloatField(blank=True, null=True)),
                ('qc_status', models.CharField(choices=[('PENDING', '待定'), ('PASS', '合格'), ('FAIL', '不合格')], db_index=True, default='PASS', max_length=20)),
                ('qc_note', models.TextField(blank=True, default='')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='cases.nipptextractionbatch')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extraction_samples', to='cases.case')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={'db_table': 'nippt_extraction_samples', 'ordering': ['created_at']},
        ),
        migrations.CreateModel(
            name='NipptLibraryBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_number', models.CharField(db_index=True, max_length=30, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', '待处理'), ('IN_PROGRESS', '处理中'), ('COMPLETED', '已完成')], db_index=True, default='DRAFT', max_length=20)),
                ('library_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={'db_table': 'nippt_library_batches', 'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='NipptLibrarySample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('MOTHER', 'Mother'), ('ALLEGED_FATHER', 'Alleged Father')], db_index=True, max_length=20)),
                ('category', models.CharField(choices=[('FEMALE_BLOOD', '女性血液'), ('MALE_BLOOD', '男性血液'), ('MALE_OTHER', '男性其他')], db_index=True, max_length=20)),
                ('case_sample_ids', models.JSONField(default=list)),
                ('source_extraction_sample_id', models.UUIDField(blank=True, null=True)),
                ('library_method', models.CharField(blank=True, default='', max_length=20)),
                ('adapter_type', models.CharField(blank=True, default='', max_length=50)),
                ('pcr_cycles', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('library_concentration', models.FloatField(blank=True, null=True)),
                ('qc_status', models.CharField(choices=[('PENDING', '待定'), ('PASS', '合格'), ('FAIL', '不合格')], db_index=True, default='PASS', max_length=20)),
                ('qc_note', models.TextField(blank=True, default='')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='cases.nipptlibrarybatch')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_samples', to='cases.case')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={'db_table': 'nippt_library_samples', 'ordering': ['created_at']},
        ),
        migrations.CreateModel(
            name='NipptPoolingBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_number', models.CharField(db_index=True, max_length=30, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', '待处理'), ('IN_PROGRESS', '处理中'), ('COMPLETED', '已完成')], db_index=True, default='DRAFT', max_length=20)),
                ('pooling_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={'db_table': 'nippt_pooling_batches', 'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='NipptPoolingSample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('MOTHER', 'Mother'), ('ALLEGED_FATHER', 'Alleged Father')], db_index=True, max_length=20)),
                ('category', models.CharField(choices=[('FEMALE_BLOOD', '女性血液'), ('MALE_BLOOD', '男性血液'), ('MALE_OTHER', '男性其他')], db_index=True, max_length=20)),
                ('case_sample_ids', models.JSONField(default=list)),
                ('source_library_sample_id', models.UUIDField(blank=True, null=True)),
                ('library_concentration', models.FloatField(blank=True, null=True)),
                ('molar_concentration', models.FloatField(blank=True, null=True)),
                ('pooling_volume', models.FloatField(blank=True, null=True)),
                ('pool_barcode', models.CharField(blank=True, default='', max_length=50)),
                ('qc_status', models.CharField(choices=[('PENDING', '待定'), ('PASS', '合格'), ('FAIL', '不合格')], db_index=True, default='PASS', max_length=20)),
                ('qc_note', models.TextField(blank=True, default='')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='cases.nipptpoolingbatch')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pooling_samples', to='cases.case')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={'db_table': 'nippt_pooling_samples', 'ordering': ['created_at']},
        ),
        migrations.CreateModel(
            name='NipptHybSeqBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_number', models.CharField(db_index=True, max_length=30, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', '待处理'), ('IN_PROGRESS', '处理中'), ('COMPLETED', '已完成')], db_index=True, default='DRAFT', max_length=20)),
                ('hyb_seq_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={'db_table': 'nippt_hybseq_batches', 'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='NipptHybSeqSample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('MOTHER', 'Mother'), ('ALLEGED_FATHER', 'Alleged Father')], db_index=True, max_length=20)),
                ('category', models.CharField(choices=[('FEMALE_BLOOD', '女性血液'), ('MALE_BLOOD', '男性血液'), ('MALE_OTHER', '男性其他')], db_index=True, max_length=20)),
                ('case_sample_ids', models.JSONField(default=list)),
                ('source_pooling_sample_id', models.UUIDField(blank=True, null=True)),
                ('sequencer', models.CharField(blank=True, default='', max_length=50)),
                ('chip_type', models.CharField(blank=True, default='', max_length=50)),
                ('read_length', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('reads_count', models.BigIntegerField(blank=True, null=True)),
                ('q30_score', models.FloatField(blank=True, null=True)),
                ('qc_status', models.CharField(choices=[('PENDING', '待定'), ('PASS', '合格'), ('FAIL', '不合格')], db_index=True, default='PASS', max_length=20)),
                ('qc_note', models.TextField(blank=True, default='')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='cases.nippthybseqbatch')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hybseq_samples', to='cases.case')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={'db_table': 'nippt_hybseq_samples', 'ordering': ['created_at']},
        ),
        migrations.CreateModel(
            name='NipptBioinfoBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_number', models.CharField(db_index=True, max_length=30, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', '待处理'), ('IN_PROGRESS', '处理中'), ('COMPLETED', '已完成')], db_index=True, default='DRAFT', max_length=20)),
                ('bioinfo_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={'db_table': 'nippt_bioinfo_batches', 'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='NipptBioinfoSample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('MOTHER', 'Mother'), ('ALLEGED_FATHER', 'Alleged Father')], db_index=True, max_length=20)),
                ('category', models.CharField(choices=[('FEMALE_BLOOD', '女性血液'), ('MALE_BLOOD', '男性血液'), ('MALE_OTHER', '男性其他')], db_index=True, max_length=20)),
                ('case_sample_ids', models.JSONField(default=list)),
                ('source_hybseq_sample_id', models.UUIDField(blank=True, null=True)),
                ('analysis_pipeline', models.CharField(blank=True, default='', max_length=50)),
                ('reference_genome', models.CharField(blank=True, default='', max_length=50)),
                ('result_file', models.CharField(blank=True, default='', max_length=200)),
                ('cpi_values', models.JSONField(blank=True, default=dict)),
                ('qc_status', models.CharField(choices=[('PENDING', '待定'), ('PASS', '合格'), ('FAIL', '不合格')], db_index=True, default='PASS', max_length=20)),
                ('qc_note', models.TextField(blank=True, default='')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='cases.nipptbioinfobatch')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bioinfo_samples', to='cases.case')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={'db_table': 'nippt_bioinfo_samples', 'ordering': ['created_at']},
        ),
    ]
