# Generated by Django 5.2.15, manually adjusted for state/DB sync

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0011_experiment_sample_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # === State-only: fields/models that exist in DB but migration state is unaware ===
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='case',
                    name='pt_number',
                    field=models.CharField(blank=True, db_index=True, help_text='Auto-assigned PT sequential number, e.g. PT00123', max_length=20, null=True, unique=True),
                ),
                migrations.AlterField(
                    model_name='casesample',
                    name='resample_number',
                    field=models.PositiveSmallIntegerField(blank=True, help_text='Resample sequence number: 1, 2, ...', null=True),
                ),
                migrations.AlterField(
                    model_name='casesample',
                    name='resample_of',
                    field=models.ForeignKey(blank=True, help_text='Points to original CaseSample if this is a resample', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resamples', to='cases.casesample'),
                ),
                migrations.CreateModel(
                    name='NipptPreProcessingBatch',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('batch_number', models.CharField(db_index=True, help_text='Auto-generated: YYYYMMDD-HH-NNN', max_length=30, unique=True)),
                        ('status', models.CharField(choices=[('DRAFT', '待处理'), ('IN_PROGRESS', '处理中'), ('COMPLETED', '已完成')], db_index=True, default='DRAFT', max_length=20)),
                        ('processing_data', models.JSONField(blank=True, default=dict)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'db_table': 'nippt_preprocessing_batches',
                        'ordering': ['-created_at'],
                    },
                ),
                migrations.CreateModel(
                    name='NipptPreProcessingSample',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('patient_name', models.CharField(max_length=200)),
                        ('role', models.CharField(choices=[('MOTHER', 'Mother'), ('ALLEGED_FATHER', 'Alleged Father')], db_index=True, max_length=20)),
                        ('category', models.CharField(choices=[('FEMALE_BLOOD', '女性血液'), ('MALE_BLOOD', '男性血液'), ('MALE_OTHER', '男性其他')], db_index=True, max_length=20)),
                        ('case_sample_ids', models.JSONField(default=list)),
                        ('sample_condition', models.CharField(blank=True, default='OK', help_text='样本情况: OK / HEMOLYZED / LOW_VOLUME / OTHER', max_length=20)),
                        ('aliquot_tubes', models.PositiveSmallIntegerField(default=3, help_text='分装管数: 女默认3, 男默认2')),
                        ('plasma_volume', models.FloatField(blank=True, help_text='血浆体积 (mL)', null=True)),
                        ('experiment_sample_type', models.CharField(blank=True, default='', help_text='操作员选择的实验样本类型', max_length=10)),
                        ('remaining_override', models.JSONField(blank=True, default=None, help_text='Manually set remaining sample types (overrides computed)', null=True)),
                        ('elution_volume', models.FloatField(blank=True, default=30, help_text='洗脱体积 (uL)', null=True)),
                        ('dna_concentration', models.FloatField(blank=True, help_text='DNA浓度 (ng/uL)', null=True)),
                        ('qc_status', models.CharField(choices=[('PENDING', '待定'), ('PASS', '合格'), ('FAIL', '不合格')], db_index=True, default='PASS', max_length=20)),
                        ('qc_note', models.TextField(blank=True, default='')),
                        ('processed_at', models.DateTimeField(blank=True, null=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='cases.nipptpreprocessingbatch')),
                        ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preprocessing_samples', to='cases.case')),
                        ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'db_table': 'nippt_preprocessing_samples',
                        'ordering': ['created_at'],
                    },
                ),
                migrations.CreateModel(
                    name='WorkflowLog',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('stage', models.CharField(db_index=True, max_length=30)),
                        ('action', models.CharField(max_length=20)),
                        ('batch_number', models.CharField(blank=True, max_length=30)),
                        ('note', models.TextField(blank=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                        ('case_sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_logs', to='cases.casesample')),
                        ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'db_table': 'nippt_workflow_logs',
                        'ordering': ['-created_at'],
                    },
                ),
            ],
            database_operations=[],
        ),
        # === ACTUAL new table ===
        migrations.CreateModel(
            name='NipptBioinfoPair',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('father_label', models.CharField(help_text='H / HA / HB / HC...', max_length=10)),
                ('is_cross_batch', models.BooleanField(default=False)),
                ('mother_source_batch', models.CharField(blank=True, default='', max_length=30)),
                ('father_source_batch', models.CharField(blank=True, default='', max_length=30)),
                ('cpi', models.FloatField(blank=True, null=True)),
                ('cpi_combined', models.FloatField(blank=True, null=True)),
                ('result', models.CharField(blank=True, choices=[('INCLUSION', 'Support'), ('EXCLUSION', 'Exclusion'), ('INCONCLUSIVE', 'Inconclusive')], db_index=True, default='', max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('report_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairs', to='cases.nipptbioinfobatch')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bioinfo_pairs', to='cases.case')),
                ('father_sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairs_as_father', to='cases.nipptbioinfosample')),
                ('mother_sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairs_as_mother', to='cases.nipptbioinfosample')),
            ],
            options={
                'db_table': 'nippt_bioinfo_pairs',
                'ordering': ['case__case_number', 'father_label'],
                'unique_together': {('batch', 'mother_sample', 'father_sample')},
            },
        ),
    ]
