# Generated by Django 5.2.15 on 2026-08-04 03:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0012_bioinfo_pair'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='nipptbioinfopair',
            name='father_concentration',
            field=models.FloatField(blank=True, help_text='父本浓度', null=True),
        ),
        migrations.AddField(
            model_name='nipptbioinfopair',
            name='father_het_ratio',
            field=models.FloatField(blank=True, help_text='父本杂纯比', null=True),
        ),
        migrations.AddField(
            model_name='nipptbioinfopair',
            name='father_layers',
            field=models.FloatField(blank=True, help_text='父本层数', null=True),
        ),
        migrations.AddField(
            model_name='nipptbioinfopair',
            name='father_y_ratio',
            field=models.FloatField(blank=True, help_text='父本Y比例', null=True),
        ),
        migrations.AddField(
            model_name='nipptbioinfopair',
            name='mother_concentration',
            field=models.FloatField(blank=True, help_text='母本浓度', null=True),
        ),
        migrations.AddField(
            model_name='nipptbioinfopair',
            name='mother_het_ratio',
            field=models.FloatField(blank=True, help_text='母本杂纯比', null=True),
        ),
        migrations.AddField(
            model_name='nipptbioinfopair',
            name='mother_layers',
            field=models.FloatField(blank=True, help_text='母本层数', null=True),
        ),
        migrations.AddField(
            model_name='nipptbioinfopair',
            name='mother_y_ratio',
            field=models.FloatField(blank=True, help_text='母本Y比例', null=True),
        ),
        migrations.AddField(
            model_name='nipptbioinfopair',
            name='qc_operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nipptbioinfopair',
            name='qc_status',
            field=models.CharField(choices=[('PENDING', '待分析'), ('ANALYZED', '已分析'), ('REVIEWED', '已审核'), ('APPROVED', '已批准')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='nipptbioinfopair',
            name='qc_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
