# Generated by Django 5.2.15 on 2026-08-04 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0013_bioinfo_pair_qc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nipptbioinfopair',
            name='qc_operator',
        ),
        migrations.RemoveField(
            model_name='nipptbioinfopair',
            name='qc_status',
        ),
        migrations.RemoveField(
            model_name='nipptbioinfopair',
            name='qc_updated_at',
        ),
        migrations.AddField(
            model_name='nipptbioinfopair',
            name='qc_flag',
            field=models.CharField(blank=True, choices=[('MALE_LOW_LAYERS', '男性层数低'), ('FEMALE_LOW_LAYERS', '女性层数低'), ('MALE_CONTAM', '男性污染'), ('FEMALE_CONTAM', '女性污染'), ('FETAL_LOW_CONC', '胎儿浓度低'), ('OTHER', '其他异常')], db_index=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='nipptbioinfopair',
            name='result',
            field=models.CharField(blank=True, choices=[('INCLUSION', '支持'), ('EXCLUSION', '不支持'), ('INCONCLUSIVE', '亲缘临界')], db_index=True, default='', max_length=20),
        ),
    ]
