# Generated by Django 5.2.15 on 2026-08-04 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0014_qc_flag_fix'),
    ]

    operations = [
        migrations.AddField(
            model_name='nipptbioinfosample',
            name='concentration',
            field=models.FloatField(blank=True, help_text='浓度', null=True),
        ),
        migrations.AddField(
            model_name='nipptbioinfosample',
            name='het_ratio',
            field=models.FloatField(blank=True, help_text='杂纯比', null=True),
        ),
        migrations.AddField(
            model_name='nipptbioinfosample',
            name='layers',
            field=models.FloatField(blank=True, help_text='层数', null=True),
        ),
        migrations.AddField(
            model_name='nipptbioinfosample',
            name='qc_flag',
            field=models.CharField(blank=True, choices=[('MALE_LOW_LAYERS', '男性层数低'), ('FEMALE_LOW_LAYERS', '女性层数低'), ('MALE_CONTAM', '男性污染'), ('FEMALE_CONTAM', '女性污染'), ('FETAL_LOW_CONC', '胎儿浓度低'), ('OTHER', '其他异常')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='nipptbioinfosample',
            name='y_ratio',
            field=models.FloatField(blank=True, help_text='Y比例', null=True),
        ),
    ]
