# Generated by Django 5.2.15 on 2026-08-05 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0015_bioinfo_sample_metrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='casesample',
            name='redo_count',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Redo sequence number: 1, 2, ...', null=True),
        ),
        migrations.AddField(
            model_name='casesample',
            name='redo_of',
            field=models.ForeignKey(blank=True, help_text='Points to original CaseSample if this is a redo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redos', to='cases.casesample'),
        ),
        migrations.AddField(
            model_name='workflowlog',
            name='batch_sample_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
