# Generated by Django 5.2.15 on 2026-08-05 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0016_redo_and_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casesample',
            name='sample_source',
            field=models.CharField(choices=[('BLOOD', '血液'), ('DBS', '血痕'), ('HAIR', '毛发'), ('SWAB', '口拭子'), ('NAIL', '指甲'), ('SEMEN', '精液'), ('TOOTHBRUSH', '牙刷'), ('CIGARETTE', '烟头'), ('BOTTLE', '水瓶'), ('BEARD', '胡须'), ('FLOSS', '牙线'), ('SEMSTAIN', '精斑'), ('GUM', '口香糖')], default='BLOOD', max_length=10),
        ),
    ]
