# Generated by Django 5.2.15 on 2026-08-05 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0017_new_sample_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('REGISTERED', '已登记'), ('RECEIVED', '已签收'), ('PRE_PROCESSING', '前处理'), ('EXTRACTION', '提取中'), ('LIBRARY_PREP', '建库中'), ('POOLING', 'Pooling'), ('HYB_SEQ', '测序中'), ('BIOINFO', '生信中'), ('REPORT_DRAFT', '报告草稿'), ('COMPLETED', '已完成'), ('HAS_FAILURE', '有失败'), ('CANCELLED', '已取消')], db_index=True, default='REGISTERED', max_length=20),
        ),
    ]
