# Generated by Django 5.2.15 on 2026-08-06 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0018_status_unification'),
    ]

    operations = [
        migrations.AddField(
            model_name='casesample',
            name='received_by_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
