# Generated by Django 5.2.15 on 2026-08-06 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0019_received_by_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='experiment_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='reviewer',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='nipptpreprocessingbatch',
            name='experiment_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nipptpreprocessingbatch',
            name='reviewer',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
