# Generated by Django 5.2.15 on 2026-08-06 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0020_operator_reviewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='operator_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='nipptpreprocessingbatch',
            name='operator_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
