# Generated by Django 5.2.15 on 2026-08-11 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0021_operator_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='nipptpoolingbatch',
            name='pool_date',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='nipptpoolingbatch',
            name='pool_time',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='nipptpreprocessingbatch',
            name='pp_date',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='nipptpreprocessingbatch',
            name='pp_time',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
