# Generated by Django 5.2.15 on 2026-08-13 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0022_pool_pp_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='nipptbioinfobatch',
            name='operator_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='nipptbioinfobatch',
            name='reviewer',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='nipptextractionbatch',
            name='operator_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='nipptextractionbatch',
            name='reviewer',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='nippthybseqbatch',
            name='operator_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='nippthybseqbatch',
            name='reviewer',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='nipptlibrarybatch',
            name='operator_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='nipptlibrarybatch',
            name='reviewer',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='nipptpoolingbatch',
            name='operator_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='nipptpoolingbatch',
            name='reviewer',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
