# Generated by Django 5.2.15 on 2026-09-07 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0023_add_operator_reviewer_batches'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='application_signed',
            field=models.CharField(blank=True, choices=[('YES', '是'), ('NO', '否'), ('WECHAT', '微信授权')], default='', help_text='申请单是否签字', max_length=10),
        ),
        migrations.AddField(
            model_name='case',
            name='collection_method',
            field=models.CharField(blank=True, choices=[('1', '本室采集'), ('2', '申请人送来'), ('3', '邮寄样本')], default='3', help_text='采集方式: 1=本室采集, 2=申请人送来, 3=邮寄样本', max_length=2),
        ),
        migrations.AlterField(
            model_name='case',
            name='multiple_gestation',
            field=models.BooleanField(blank=True, default=False, help_text='单双胎: null=客户未填, False=单胎, True=双胎', null=True),
        ),
    ]
