# Generated by Django 5.2.15 on 2026-09-10 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0024_nippt_registration_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='casesample',
            name='receipt_note',
            field=models.TextField(blank=True, default='', help_text='签收备注（样本情况/与登记不一致等注意事项）'),
        ),
    ]
