# Generated by Django 5.2.15 on 2026-09-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0025_case_sample_receipt_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nipptextractionsample',
            name='elution_volume',
            field=models.FloatField(blank=True, default=55, null=True),
        ),
    ]
