# Generated by Django 5.2.15 on 2026-09-16 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0026_extraction_elution_default_55'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='casesample',
            name='reactivated',
            field=models.BooleanField(default=False, help_text='重做激活标志：用其他样本重做时置True，出现在前处理待做列表，进入前处理批次后自动清除'),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('REGISTERED', '已登记'), ('RECEIVED', '已签收'), ('PRE_PROCESSING', '前处理'), ('EXTRACTION', '提取中'), ('LIBRARY_PREP', '建库中'), ('POOLING', 'Pooling'), ('HYB_SEQ', '测序中'), ('BIOINFO', '生信中'), ('REPORT_DRAFT', '报告草稿'), ('COMPLETED', '已完成'), ('HAS_FAILURE', '有失败'), ('HAS_RESAMPLE', '有重采'), ('CANCELLED', '已取消')], db_index=True, default='REGISTERED', max_length=20),
        ),
        migrations.CreateModel(
            name='NipptPlasmaTubeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before_count', models.PositiveSmallIntegerField(default=0)),
                ('after_count', models.PositiveSmallIntegerField(default=0)),
                ('reason', models.CharField(max_length=50)),
                ('batch_number', models.CharField(blank=True, default='', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plasma_tube_logs', to='cases.case')),
                ('case_sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plasma_tube_logs', to='cases.casesample')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'nippt_plasma_tube_logs',
                'ordering': ['created_at'],
            },
        ),
    ]
