# Generated by Django 5.2.15 on 2026-09-20 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0027_casesample_reactivated_alter_case_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='nipptbioinfopair',
            name='report_audited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nipptbioinfopair',
            name='report_auditor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nipptbioinfopair',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to='nippt_reports/%Y%m/'),
        ),
        migrations.AddField(
            model_name='nipptbioinfopair',
            name='report_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='nipptbioinfopair',
            name='report_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nipptbioinfopair',
            name='report_reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
