# Generated by Django 5.2.15 on 2026-09-21 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0028_nipptbioinfopair_report_audited_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casesample',
            name='receipt_location',
            field=models.CharField(blank=True, choices=[('XIAMEN', '厦门'), ('HONGKONG', '香港')], default='', help_text='签收地: XIAMEN=厦门 / HONGKONG=香港', max_length=20),
        ),
    ]
