# Generated by Django 5.2.15 on 2026-09-24 05:42
# 手工调整为 SeparateDatabaseAndState：
#   migration 0012 把 WorkflowLog.id 误声明为 BigAutoField，而 DB 实际是
#   uuid DEFAULT gen_random_uuid()（与其余 14 张 nippt 表一致）。
#   模型现改为 UUIDField 以对齐，本迁移只同步 Django 状态，不产生任何 DDL
#   （列类型已经是 uuid，DROP DEFAULT / 重建主键都无意义且有多余风险）。
import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0029_casesample_receipt_location'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='workflowlog',
                    name='id',
                    field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
            ],
            database_operations=[],
        ),
    ]
